### ISSUE TITLE
失效了

### ISSUE THREAD

**Issue by six220mao** [biancangming/wtv#11]
不能看了，能不能更新下，谢谢

**Comment by megaslx** [comment]
的确，看不了了

**Comment by biancangming** [comment]
@megaslx @six220mao 好久没更新了，最近会抽时间整理一波，建议进群，群内分享的大神很多的。

**Comment by six220mao** [comment]
> @megaslx @six220mao 好久没更新了，最近会抽时间整理一波，建议进群，群内分享的大神很多的。

群号多少啊，点了那个加群链接没有反应

**Comment by afghn** [comment]
> > @megaslx @six220mao 好久没更新了，最近会抽时间整理一波，建议进群，群内分享的大神很多的。
> 
> 群号多少啊，点了那个加群链接没有反应

雀食

**Comment by woboo110** [comment]
> @megaslx @six220mao 好久没更新了，最近会抽时间整理一波，建议进群，群内分享的大神很多的。

群号多少

**Comment by iamsnn** [comment]
能求一个更新版的群邀请链接吗？现有的那个打不开了。。。多谢🙏

**Comment by Yilian1929** [comment]
求入群

**Comment by MikeJinhua** [comment]
群链接好像也失效了。特意更新最新的QQ还是不行。

**Comment by hy-allron** [comment]
+1
