### ISSUE TITLE
添加测速功能？

### ISSUE THREAD

**Issue by cicai1631** [biancangming/wtv#14]
比如一个台，有很多m3u地址，如何找到最快的几个，其余的丢弃

**Comment by Derek-G** [comment]
源测速我个人感觉不应是短时间的一次性测速，应该是持久性的稳定性检测以观察速度的平均值判断源是否稳定可靠。仅代表个人意见哈作者可以酌情考量，感谢作者开发这款工具

**Comment by Echenr** [comment]
分享一下我用wtv的体会，我是用来看电视台的比赛直播的，一般可以扫到十几个源，但是一到直播开始大多数源都会变卡，可能是用的人多了，所以需要手动找不卡的源。

**Comment by biancangming** [comment]
现在增加了简单测试功能，但是直播源是否通畅的决定因素很多，仅供参考使用
