### ISSUE TITLE
windows 系统下最小化后检测进度会暂停

### ISSUE THREAD

**Issue by Derek-G** [biancangming/wtv#21]
云端导入后开始检测，软件最小化20min后打开发现进度未发生变化，恢复窗口会继续进行检测

**Comment by biancangming** [comment]
> 云端导入后开始检测，软件最小化20min后打开发现进度未发生变化，恢复窗口会继续进行检测

谢谢提出的意见，后续会跟进并改进

**Comment by biancangming** [comment]
没有发现这个问题，暂时关闭了
