### ISSUE TITLE
窗口最大化和还原图标反着

### ISSUE THREAD

**Issue by ibin7777** [biancangming/wtv#22]
<img width="179" alt="image" src="https://user-images.githubusercontent.com/64576479/166141303-a690dde2-6765-459a-a95e-cd77cce1a739.png">
<img width="199" alt="image" src="https://user-images.githubusercontent.com/64576479/166141312-8c3b7291-5a3f-4abf-b69e-b40d67392179.png">
如图，窗口和最大化的突变应该反过来，更符合逻辑

**Comment by biancangming** [comment]
谢谢，修正了下虽然不完美，将就的用吧 @ibin7777
