### ISSUE TITLE
v0.7版本检测完后导出把无效源也导出了

### ISSUE THREAD

**Issue by xianshancom** [biancangming/wtv#24]
v0.7版本检测完成后，导出，把无效源也导出了；
除非在列表上右键去除无效源再导出才正确。

**Comment by biancangming** [comment]
现在操作是这样的，有时候别人只是想做个整合。不想剔除无效源，这样更灵活些



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月4日(周三) 上午10:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [biancangming/wtv] v0.7版本检测完后导出把无效源也导出了 (Issue #24)




 
v0.7版本检测完成后，导出，把无效源也导出了；
 除非在列表上右键去除无效源再导出才正确。

**Comment by biancangming** [comment]
最新测试版0.1测试了，在群里下载吧
