### ISSUE TITLE
请问可以添加自动分组和添加台标么？

### ISSUE THREAD

**Issue by mulaxiusi** [biancangming/wtv#25]
可以的话希望添加内地央视，内地卫视，内地地方台，港澳台，海外等分组，自动识别名字对应分组。并且添加http://epg.51zmt.top:8000/ 的台标进M3U文件。这样配合Xteve和其他媒体库是不是就可以自动添加台标，方便筛选那些台需要哪些台不需要？

**Comment by mulaxiusi** [comment]
可以在http://epg.51zmt.top:8000/完成添加台标的操作，分组选择还是可以有

**Comment by biancangming** [comment]
分组和台标这个我会考虑的，只是个人时间有限，感谢意见

**Comment by biancangming** [comment]
这个0.1版本已经有了，只是不怎么完善，也不计划做这么多了
