### ISSUE TITLE
请问安卓食用wtv的最佳姿势是什么？

### ISSUE THREAD

**Issue by typenoob** [biancangming/wtv#27]

**Comment by biancangming** [comment]
1. 在wtv搜索完成，找到合适的节目
2. 用这个网站生成一个在线的播放链接维护起来，http://online.bianbingdang.com/
3. 找个安卓壳子，例如DIYP、IPTVpro，导入即可使用

需要说明的是，我的目标是开发一款辅助工具。而不是一个播放软件，所以怎么播放不是本软件开发的重点，原因是市场上各种播放器已经太多了
