### ISSUE TITLE
大佬，可不可以检测延迟/码率之类的详细信息？

### ISSUE THREAD

**Issue by iancsy** [biancangming/wtv#28]
这个应该是很常见问题，想在一批源里看哪些最适合当地播放，挑出最清晰速度最快的源来，网上好像没看到有类似的工具，有木有计划加进去啊…公众号已关注

**Comment by biancangming** [comment]
这个可以研究下ffmpeg，这方面是专业的，只不过是个命令行的软件。后边有空了给做个页面，现在网友的需求还很多，还是要谅解下 @iancsy
