### ISSUE TITLE
utf8格式的文本导入后中文乱码

### ISSUE THREAD

**Issue by yunnysunny** [biancangming/wtv#35]
导入utf8格式的txt文本文档，显示中文乱码
![image](https://user-images.githubusercontent.com/734818/187838911-486ed0e5-d63e-4fab-b095-fc39b4efc1eb.png)
源文件如下：
[tv_2022-02-28.txt](https://github.com/biancangming/wtv/files/9467122/tv_2022-02-28.txt)

**Comment by biancangming** [comment]
希望关注一个橙子pro公众号，本周更新全新版本将完全解决这个问题

**Comment by biancangming** [comment]
最新版 一个橙子pro工具箱已经解决
