### ISSUE TITLE
无法清除老的订阅源数据

### ISSUE THREAD

**Issue by babyvox550** [biancangming/wtv#37]
无法清除老的订阅源数据
![image](https://user-images.githubusercontent.com/13328183/191763078-1977838d-8c68-4e37-a2eb-ca6b5ff61915.png)
订阅清空了
![image](https://user-images.githubusercontent.com/13328183/191763193-0228b8b9-f3e0-42ab-b8ad-09a012c72020.png)
然而，搜索后，出来大量的结果

**Comment by biancangming** [comment]
在电脑文档下面找到文件夹yigechengzipro
进入 db 文件夹，看到文件 wtvsubscribe.db，直接删除，重启软件。删不掉的话先关掉软件
