### ISSUE TITLE
CCTV突然看不了了

### ISSUE THREAD

**Issue by Deckard-f-Cain** [biancangming/wtv#7]
本来这几天用国内的CN.M3U用的好好的，也一直能看欧洲杯直播，今天下午突然都不行了，都不能打开了。。。老大劳烦更新一下啊！

**Comment by afghn** [comment]
不是很稳，用亿家直播吧

**Comment by biancangming** [comment]
用扫源工具检测下，非专业渠道失效是常事，建议到QQ群咨询大佬们
