### ISSUE TITLE
白屏

### ISSUE THREAD

**Issue by 4userpro** [biancangming/wtv#9]
我操作问题？解压打开后只有白屏

**Comment by biancangming** [comment]
请反馈下如下信息，如下

版本	Windows 10 专业版
版本号	21H1
操作系统内部版本	19043.1052
.net版本 1.7

**Comment by arho14** [comment]
一样~

**Comment by biancangming** [comment]
https://github.com/biancangming/wtv/issues/8#issuecomment-887980076  新增兼容包，下载32位兼容包，看能否解决

**Comment by jadkg** [comment]
我打开也是白屏
版本	Windows 10 专业版
版本号	21H1
安装日期	‎2021/‎7/‎15
操作系统内部版本	19043.1151
体验	Windows Feature Experience Pack 120.2212.3530.0

**Comment by coolyzp** [comment]
> [#8 (comment)](https://github.com/biancangming/wtv/issues/8#issuecomment-887980076) 新增兼容包，下载32位兼容包，看能否解决
白屏
![image](https://user-images.githubusercontent.com/37400863/130441070-0ddece13-5a3f-4afc-a50b-e7be47213537.png)
版本	Windows 10 专业工作站版
版本号	21H1
安装日期	‎2020/‎9/‎26
操作系统内部版本	19043.1200
体验	Windows Feature Experience Pack 120.2212.3740.0
